[project]
name = "ccbt-2025-parallel-botanical-garden-proto"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "googletrans>=4.0.2",
    "loguru>=0.7.3",
    "python-osc>=1.9.3",
]
